GET http://localhost:27017/users
###

GET http://localhost:27017/users/12

###

POST http://localhost:27017/users
Content-Type: application/json

{
  "name": "John Doe",
  "userToChannel": "1234567890"
}